import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { GatewayPaths } from '../paths.js';
import { ensureGatewayPaths } from './files.js';
import type { CredentialInput, CredentialSummary, ManagementOptions, OperationResult } from './types.js';

interface AccountEntry {
  value: string;
}

interface McpCredential {
  active: string;
  authType: CredentialSummary['authType'];
  envVar: string;
  accounts: Record<string, AccountEntry>;
}

export type CredentialStore = Record<string, McpCredential>;

export function loadCredentialStore(paths: GatewayPaths): CredentialStore {
  if (!existsSync(paths.credentialsPath)) return {};
  try {
    return JSON.parse(readFileSync(paths.credentialsPath, 'utf-8')) as CredentialStore;
  } catch {
    return {};
  }
}

export function saveCredentialStore(paths: GatewayPaths, store: CredentialStore): void {
  writeFileSync(paths.credentialsPath, `${JSON.stringify(store, null, 2)}\n`, 'utf-8');
}

export function summarizeCredential(store: CredentialStore, mcpName: string): CredentialSummary | undefined {
  const credential = store[mcpName];
  if (!credential) return undefined;
  const active = credential.accounts[credential.active];
  return {
    authType: credential.authType,
    envVar: credential.envVar,
    active: credential.active || undefined,
    accountCount: Object.keys(credential.accounts).length,
    maskedValue: active ? maskSecret(active.value) : undefined,
  };
}

export function writeCredential(paths: GatewayPaths, input: CredentialInput): void {
  const store = loadCredentialStore(paths);
  const authType = input.authType ?? 'env_token';
  if (!store[input.mcpName]) {
    store[input.mcpName] = { active: input.label, authType, envVar: input.envVar, accounts: {} };
  }
  store[input.mcpName].authType = authType;
  store[input.mcpName].envVar = input.envVar;
  store[input.mcpName].accounts[input.label] = { value: input.value };
  if (!store[input.mcpName].active || !store[input.mcpName].accounts[store[input.mcpName].active]) {
    store[input.mcpName].active = input.label;
  }
  saveCredentialStore(paths, store);
  syncGatewayEnv(paths, store);
}

export function switchCredentialInStore(paths: GatewayPaths, mcpName: string, label: string): boolean {
  const store = loadCredentialStore(paths);
  const credential = store[mcpName];
  if (!credential?.accounts[label]) return false;
  credential.active = label;
  saveCredentialStore(paths, store);
  syncGatewayEnv(paths, store);
  return true;
}

export function deleteCredentialFromStore(paths: GatewayPaths, mcpName: string, label?: string): boolean {
  const store = loadCredentialStore(paths);
  const credential = store[mcpName];
  if (!credential) return false;
  if (!label) {
    delete store[mcpName];
  } else {
    if (!credential.accounts[label]) return false;
    delete credential.accounts[label];
    if (credential.active === label) credential.active = Object.keys(credential.accounts)[0] ?? '';
    if (Object.keys(credential.accounts).length === 0) delete store[mcpName];
  }
  saveCredentialStore(paths, store);
  syncGatewayEnv(paths, store);
  return true;
}

export function renameCredentialInStore(paths: GatewayPaths, fromName: string, toName: string): boolean {
  if (fromName === toName) return false;
  const store = loadCredentialStore(paths);
  if (!store[fromName]) return false;
  if (store[toName]) throw new Error(`"${toName}" 認證已存在`);
  store[toName] = store[fromName];
  delete store[fromName];
  saveCredentialStore(paths, store);
  syncGatewayEnv(paths, store);
  return true;
}

export function syncGatewayEnv(paths: GatewayPaths, store = loadCredentialStore(paths)): void {
  const lines = [
    '# Multi-MCP Gateway - credentials generated by the VS Code extension or management API',
    '# Manage these values from the Multi-MCP VS Code activity bar.',
    '',
  ];
  for (const [mcpName, credential] of Object.entries(store)) {
    const active = credential.accounts[credential.active];
    if (!active || !credential.envVar) continue;
    lines.push(`# --- ${mcpName} (${credential.active}) ---`);
    lines.push(`${credential.envVar}=${active.value}`);
    lines.push('');
  }
  writeFileSync(paths.envPath, lines.join('\n'), 'utf-8');
}

export function maskSecret(value: string): string {
  if (value.length <= 12) return '****';
  return `${value.slice(0, 4)}...${value.slice(-4)}`;
}

export function upsertCredential(input: CredentialInput, options: ManagementOptions = {}): OperationResult {
  const paths = ensureGatewayPaths(options);
  writeCredential(paths, input);
  return { ok: true, changed: true, message: `"${input.mcpName}" 認證已更新` };
}

export function switchCredential(mcpName: string, label: string, options: ManagementOptions = {}): OperationResult {
  const paths = ensureGatewayPaths(options);
  const changed = switchCredentialInStore(paths, mcpName, label);
  return { ok: changed, changed, message: changed ? `"${mcpName}" 已切換到 "${label}"` : `找不到 "${label}"` };
}

export function deleteCredential(mcpName: string, label?: string, options: ManagementOptions = {}): OperationResult {
  const paths = ensureGatewayPaths(options);
  const changed = deleteCredentialFromStore(paths, mcpName, label);
  return { ok: changed, changed, message: changed ? `"${mcpName}" 認證已刪除` : `找不到 "${mcpName}" 認證` };
}
